# Generated by Django 6.0.8 on 2026-08-07 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAndWorkerAvailabilityApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='is_preset',
        ),
        migrations.AddField(
            model_name='worker',
            name='is_present',
            field=models.BooleanField(default=True, verbose_name='Preset'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='RoomAndWorkerAvailabilityApp.room', verbose_name='Room number'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Reserver id'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR')], max_length=25),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(choices=[('Mayor', 'Mayor'), ('Secretary', 'Secretary'), ('Administrator', 'Administrator')], max_length=30, verbose_name='Position'),
        ),
    ]
