# Generated by Django 6.0.8 on 2026-08-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAndWorkerAvailabilityApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worker',
            name='unique_worker',
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_worker'),
        ),
    ]
