# Generated by Django 6.0.8 on 2026-08-05 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('pk', models.CompositePrimaryKey('room_number', 'room_floor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.PositiveIntegerField(default=1, verbose_name='Numer pokoju')),
                ('room_floor', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Piętro')),
                ('room_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nazwa pokoju')),
                ('building_name', models.CharField(blank=True, max_length=1, null=True, verbose_name='Nazwa budynku')),
                ('additional_room_info', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Dodatkowe informacje')),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Sale',
            },
        ),
    ]
