# Generated by Django 6.0.8 on 2026-08-05 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAvailabilityApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='additional_room_info',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building_name',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Building name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_floor',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Room name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Room number'),
        ),
    ]
