# Generated by Django 6.0.8 on 2026-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAvailabilityApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='pk',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False, verbose_name='Room number'),
        ),
    ]
