# Generated by Django 6.0.8 on 2026-08-06 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAvailabilityApp', '0002_remove_room_pk_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_preset',
            field=models.BooleanField(default=False, verbose_name='Preset'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=30, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='reason_of_absence',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Reason of absence'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='start_of_absence',
            field=models.DateField(blank=True, null=True, verbose_name='Start of the absence'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('start_of_reservation', models.DateField(verbose_name='Start of the reservation')),
                ('end_of_reservation', models.DateField(verbose_name='End of the reservation')),
                ('description_of_event', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Description of event')),
                ('pk', models.CompositePrimaryKey('worker', 'room', 'start_of_reservation', 'end_of_reservation', blank=True, editable=False, primary_key=True, serialize=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomAvailabilityApp.room', verbose_name='Room number')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reserver id')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
